make runc patch non-fatal

diff --git a/.github/workflows/build-AB-zyc.yml b/.github/workflows/build-AB-zyc.yml
--- a/.github/workflows/build-AB-zyc.yml
+++ b/.github/workflows/build-AB-zyc.yml
@@ -142,7 +142,7 @@ jobs:
       - name: 应用runc补丁
         run: |
           cd $GITHUB_WORKSPACE/kernel_workspace
-          wget https://github.com/fate-think/LXC-DOCKER-KernelSU_Action/releases/download/1.0.0/runcpatch.sh
+          wget https://github.com/fate-think/LXC-DOCKER-KernelSU_Action/releases/download/1.0.0/runcpatch.sh || echo 'runcpatch not found, skip'
           chmod a+x runcpatch.sh
           if [ -f android-kernel/kernel/cgroup.c ]; then ./runcpatch.sh android-kernel/kernel/cgroup.c; fi
           if [ -f android-kernel/kernel/cgroup/cgroup.c ]; then ./runcpatch.sh android-kernel/kernel/cgroup/cgroup.c; fi
